package payrexxsdk

import (
	"github.com/sosodev/duration"
)

type PaylinkStatus string

const (
	PaylinkStatusWaiting    GatewayStatus = "waiting"
	PaylinkStatusConfirmed  GatewayStatus = "confirmed"
	PaylinkStatusAuthorized GatewayStatus = "authorized"
	PaylinkStatusReserved   GatewayStatus = "reserved"
)

// Paylink is a combination of Body & Head representing a
// complete Paylink
type Paylink struct {
	PaylinkHead
	PaylinkBody
	Purpose map[string]string
}

// PaylinkBody represents the data needed to create a Paylink at payrexx
type PaylinkBody struct {
	// (REQ) Title of the payment shown on the page
	Title string `json:"title"`
	// (REQ) Description of the payment shown on the page
	Description string `json:"description"`
	// (REQ) Your internal reference id
	ReferenceId string `json:"referenceId"`
	// (REQ) The Purpose of the payment
	Purpose string `json:"purpose"`
	// (REQ) Amount of payment in cents
	Amount int32 `json:"amount"`
	// (OPT) VAT Rate Percentage (nil meaning not set)
	VatRate float32 `json:"vatRate,omitempty"`
	// (REQ) Currency of payment (ISO code)
	Currency string `json:"currency"`
	// (OPT) Psp represents a list of which payment method is allowed
	Psp []int32 `json:"psp,omitempty"`
	// (OPT) PM is list of payment mean names to display
	Pm []string `json:"pm,omitempty"`
	// (OPT) Sku meaning product stock keeping unit
	Sku string `json:"sku,omitempty"`
	// (opt) Whether charge payment manually at a later date (type authorization).
	PreAuthorization bool `json:"preAuthorization"`
	// (opt) Whether charge payment manually at a later date (type reservation).
	Reservation bool `json:"reservation"`
	// (opt) This is an internal name of the payment page. This name will be displayed to the administrator only.
	Name string `json:"name,omitempty"`
	// (OPT) The contact data fields which should be displayed
	// todo: add fields
	// (OPT)
	HideFields bool `json:"hideFields"`
	// (OPT) Only available for Concardis PSP and if the custom ORDERID option is activated in PSP settings in Payrexx administration. This ORDERID will be transferred to the Payengine.
	ConcardisOrderId string `json:"concardisOrderId,omitempty"`
	// (OPT) Custom pay button text.
	ButtonText string `json:"buttonText"`
	// (OPT) Expiration date for link. (Format Y-m-d)
	ExpirationDate string `json:"expirationDate,omitempty"`
	// (OPT) URL to redirect to after successful payment.
	SuccessRedirectUrl string `json:"successRedirectUrl,omitempty"`
	// (OPT) URL to redirect to after failed payment.
	FailedRedirectUrl string `json:"failedRedirectUrl,omitempty"`
	// (OPT) Defines whether the payment should be handled as subscription.
	SubscriptionState bool `json:"subscriptionState"`
	// (OPT) Payment interval (converted from ISO 8601)
	SubscriptionInterval duration.Duration `json:"subscriptionInterval,omitempty"`
	// (OPT) Duration of subscription (converted from ISO 8601)
	SubscriptionPeriod duration.Duration `json:"subscriptionPeriod,omitempty"`
	// (OPT) Defines the period, in which a subscription can be canceled. (converted from ISO 8601)
	SubscriptionCancellationInterval duration.Duration `json:"subscriptionCancellationInterval,omitempty"`
	// (OPT) Provide your customers file attachments.
	// todo: add attachments of type file
}

func NewPaylinkBody(title, description, referenceId, currency string, purpose string, amount int32) *PaylinkBody {
	return &PaylinkBody{
		Title:       title,
		Description: description,
		ReferenceId: referenceId,
		Purpose:     purpose,
		Amount:      amount,
		Currency:    currency,
	}
}

// PaylinkHead represents the data which gets generated by creating
// a gateway with Payrexx
type PaylinkHead struct {
	ID        int32         `json:"id"`
	Hash      string        `json:"hash"`
	Link      string        `json:"link"`
	Invoices  []string      `json:"invoices"`
	Api       bool          `json:"api"`
	CreatedAt int32         `json:"created_at"`
	Status    PaylinkStatus `json:"status"`
}
